labstep/comment.py
labstep/entity.py
labstep/experiment.py
labstep/file.py
labstep/protocol.py
labstep/resource.py
labstep/tag.py
labstep/user.py
labstep/workspace.py
tests/test_experiments.py
tests/test_protocol.py
tests/test_resource.py
tests/test_user.py

- entityName stored as Class Attribute
- entity methods (new, edit, get, getMany) take entityClass instead of entityName
- entity methods (new, edit, get, getMany) return entities with the correct class

All method return entities of the correct class

---

CONTRIBUTING.md
docs/source/example_uses.rst
examples/download_file.py
labstep/comment.py
labstep/config.py
labstep/file.py
labstep/user.py
labstep/workspace.py
tests/test_experiment.py
tests/test_metadata.py
tests/test_order_request.py
tests/test_protocol.py
tests/test_resource.py
tests/test_resource_category.py
tests/test_resource_item.py
tests/test_resource_location.py
tests/test_tag.py
tests/test_user.py
tests/test_workspace.py

- Allow saving and retrieval of Labstep files

File download

---

examples/changing_permissions.py
labstep/experiment.py
labstep/orderRequest.py
labstep/permissions.py
labstep/protocol.py
labstep/resource.py
labstep/resourceCategory.py
labstep/workspace.py
tests/test_sharing.py

- Adds ability to share content with other Workspaces and transfer ownership

Permissions

---

examples/getting_new_order_requests.py
labstep/orderRequest.py
labstep/user.py
tests/test_user.py

- add option for filtering order requests by status and tag

Filter Order requests by status and tag

---

labstep/comment.py
setup.py

- Fixed bug attaching files to comments

Release 2.1.1

---

labstep/user.py
labstep/workspace.py

- Method for creating a new user
- Method for sending workspace invites via email.

New Users and Workspace Invites

---

labstep/comment.py
labstep/experiment.py
tests/test_experiment.py

- Adds ability to get and add comments to steps and comments.

Comments on steps and comments

---

examples/changing_permissions.py
labstep/config.py
requirements.txt
setup.py

- Added ability to get and add comments to steps.
- Added ability to get and add comments to comments.

Release 2.3.0

---

tests/test_experiment.py

@BarneyLabstep you won't like it as I'm mainly removing tests here – they relied on a backend bug to even pass, so I will no be happily continuing along making them pass
There is some serious work needed on this repo (which I'm very greatful for not having to be involved in) so let's deal with the immediate issues and then decide if we want to make a time commitment to fix it

Making sure the functional tests pass

---

.circleci/config.yml
setup.py

Please don't "merge" – instead use "squash and merge" button below
This PR has a very high commits/files changed ratio, as it was iterative work on just one file ;-)

Boilerplate PyPI publication

---

labstep/entity.py
labstep/experiment.py
labstep/protocol.py
tests/test_experiment.py
tests/test_experiment_protocol.py

- Method to add Materials to Experiment
- Method to add Materials to ExperimentProtocol
- Method to get Materials on Experiment.

Managing Materials on Experiments and ExperimentProtocols

---

labstep/entity.py
labstep/experiment.py
labstep/primaryEntity.py
labstep/protocol.py
labstep/resource.py
labstep/resourceCategory.py
labstep/resourceLocation.py
labstep/tag.py
labstep/workspace.py
tests/test_experiment.py
tests/test_protocol.py

- Fix to allow editing of Protocol content state
- Fix to allow editing of Experiment description
- Method to allow creation of NewVersion of Protocol

Editing Protocol and Experiment Content State

---

examples/protocol_add_tables.py
labstep/experiment.py
labstep/protocol.py
tests/fixtures.py
tests/test_experiment_protocol.py
tests/test_protocol.py

- Protocols and ExperimentProtocols now use the updated ProseMirror JSON structure. 
- Now set using parameter 'body'

Update to how protocol body is set

---

labstep/sharelink.py
labstep/user.py
labstep/workspace.py

-  Added method getMembers and getSharelink to Workspace class
-  Added method acceptSharelink to User class

Members and Sharelinks

---

labstep/comment.py
labstep/experiment.py
labstep/metadata.py
labstep/orderRequest.py
labstep/resource.py
labstep/resourceCategory.py
labstep/resourceItem.py
labstep/version.py

- Fixed bug where `addComment` with files weren't working
- Field type `file` now supported for `addMetadata` and `addDataElement` methods ( specify `filepath` to point to file to upload)

Release 2.7.1

---

examples/resource_import.py
labstep/experiment.py

- Added `addTable` method to Experiment class to allow tables to be added to experiment entries.

Add tables to experiments

---

labstep/experiment.py
labstep/version.py

- `addTable` on `ExperimentProtocol` and `Experiment`

Release 2.7.2

---

labstep/collection.py
labstep/experiment.py
labstep/protocol.py
labstep/user.py
labstep/workspace.py
tests/fixtures.py
tests/test_collection.py
tests/test_experiment.py
tests/test_protocol.py
tests/test_workspace.py

- Collection
- `Collection.edit`
- `Collection.delete`
- `Experiment.addToCollection`
- `Experiment.removeFromCollection`
- `Experiment.getCollections`
- `Protocol.addToCollection`
- `Protocol.removeFromCollection`
- `Protocol.getCollections`
- `Workspace.getCollections`
- `Workspace.newCollection`
- `User.getExperiments` accepts `collection_id`
- `Workspace.getExperiments` accepts `collection_id`
- `User.getProtocols` accepts `collection_id`
- `Workspace.getProtocols` accepts `collection_id`

Collections

---

labstep/helpers.py
labstep/metadata.py

- Experiment data now has to be fetched in a separate API call

Metadata Refactor

---

labstep/converter.py

Add a converter to parse HTML into the JSON format used in protocols and experiment entries

HTML Converter

---

labstep/version.py

- Added converter to parse HTML to JSON

Release 2.8.1

---

labstep/entity.py
labstep/experiment.py
labstep/version.py

- Creating experiment with entry was broken

Release 2.8.2

---

.readthedocs.yaml
docs/requirements.txt
requirements.txt

sphinx_design added to:
- docs/requirements.txt
- requirements.txt

Update sphinx requirements
